[package]
name = "pttkey"
version = "0.2.0"
edition = "2021"

[dependencies]
evdev = "0.12"
anyhow = "1.0"
which = "5.0"
ctrlc = "3.5.1"
rodio = { version = "0.19", default-features = false, features = ["mp3", "wav", "vorbis"] }
